# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_triage_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.SmallIntegerField(
                choices=[(1, b"tv"), (2, b"movie"), (2, b"conversion-failed"), (3, b"converted")], default=2
            ),
        ),
    ]
