# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='media_type',
        ),
    ]
