# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 20:05
from __future__ import unicode_literals
import datetime
from django.utils import timezone

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def tomorrow():
    return timezone.now() + datetime.timedelta(days=1)


def random_uuid() -> str:
    return uuid.uuid4().hex


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_auto_20171024_1557"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieAccessToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expiration_date", models.DateField(default=tomorrow)),
                ("token", models.CharField(default=random_uuid, max_length=32)),
                ("movie", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.Movie")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
