# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_movieaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieaccesstoken",
            name="expiration_date",
            field=models.DateTimeField(default=movies.models.tomorrow),
        ),
    ]
