# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 20:15
from __future__ import unicode_literals
import datetime
from django.utils import timezone
from django.db import migrations, models


def tomorrow():
    return timezone.now() + datetime.timedelta(days=1)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_movieaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieaccesstoken",
            name="expiration_date",
            field=models.DateTimeField(default=tomorrow),
        ),
    ]
