# Generated by Django 3.0.7 on 2020-08-20 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0011_starredmovie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_starred",
        ),
    ]
