# Generated by Django 3.0.7 on 2020-12-14 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0012_remove_movie_is_starred"),
    ]

    operations = [
        migrations.RenameModel("Movie", "Episode"),
        migrations.RenameModel("MovieAccessToken", "EpisodeAccessToken"),
        migrations.RenameModel("MovieWatchStatus", "EpisodeWatchStatus"),
        migrations.RenameField(
            model_name="episodeaccesstoken",
            old_name="movie",
            new_name="episode",
        ),
        migrations.RenameField(
            model_name="episodewatchstatus",
            old_name="movie",
            new_name="episode",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="rating",
        ),
    ]
