# Generated by Django 3.0.7 on 2021-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_auto_20201214_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="triage_path",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
