# Generated by Django 3.2.13 on 2022-08-21 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0014_auto_20210401_0802"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="original_extension",
        ),
    ]
