# Generated by Django 3.2.23 on 2023-12-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_episode_original_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='conversion_status',
        ),
    ]
