# Generated by Django 3.2.23 on 2023-12-26 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0016_remove_episode_conversion_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EpisodeAccessToken",
        ),
    ]
