# Generated by Django 5.2.8 on 2025-11-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0018_rename_eng_subtitles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="episodewatchstatus",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="starredmovie",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
