# Generated by Django 5.2.8 on 2025-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0019_alter_episode_id_alter_episodewatchstatus_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
