# Generated by Django 5.2.8 on 2025-11-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0020_episode_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="duration",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
