# Generated by Django 6.0.1 on 2026-01-17 18:35

from django.db import migrations
from django.conf import settings


def rename_files(apps, schema_editor):
    for path in settings.MOVIE_LIBRARY_PATH.iterdir():
        # Fix mangled subtitle names from previous migration
        if path.suffix.lower() in (".srt", ".vtt"):
            lang_suffix = "".join([s for s in path.suffixes if s in (".eng", ".fre", ".ger")])
            new_name = path.stem.rstrip("".join(path.suffixes)) + lang_suffix + path.suffix  # "file.eng.vtt"
            path.rename(path.with_name(new_name))


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0022_auto_20260117_1802"),
    ]

    operations = [
        migrations.RunPython(rename_files),
    ]
