# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('authentication.torrents', 'Download and manage torrents'), ('authentication.movies_watch', 'Watch and download movies'), ('authentication.movies_manage', 'Manage the movie library'), ('authentication.finances', 'Use the finances feature'), ('authentication.habits', 'Use the habits feature')),
            },
        ),
    ]
