# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesspermissions",
            options={
                "managed": False,
                "permissions": (
                    ("torrents", "Download and manage torrents"),
                    ("movies_watch", "Watch and download movies"),
                    ("movies_manage", "Manage the movie library"),
                    ("finances", "Use the finances feature"),
                    ("habits", "Use the habits feature"),
                ),
            },
        ),
    ]
