# Generated by Django 5.2.8 on 2025-11-23 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_auto_20210823_1040"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesspermissions",
            options={
                "managed": False,
                "permissions": (
                    ("torrents", "Download and manage torrents"),
                    ("movies_manage", "Manage the movie library"),
                ),
            },
        ),
    ]
