# Generated by Django 5.2.8 on 2025-11-30 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_accesspermissions_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessPermissions",
        ),
    ]
