# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('minimum_successful_days', models.IntegerField(default=7)),
                ('days_per_period', models.IntegerField(default=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitOccurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurences', to='habits.Habit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
